package de.tuhh.diss.warehouse;
import de.tuhh.diss.io.SimpleIO;

/*
 * when the statement below is changed, check the corresponding statement in printPackets() in the bottom iof the code!!
 */
//import de.tuhh.diss.warehouse.WarehouseManagement;
import de.tuhh.diss.warehouse.WarehouseManagement;
import de.tuhh.diss.warehouse.sim.*;

public class WarehouseTest {
	
	/*setting up a new WarehouseManagement*/
	private static WarehouseManagement warehouseManagement = new WarehouseManagement();

	public static void main () {
		fillWarehouse();
	}
	public static void fillWarehouse(){
			for(int i =0; i< 100; i++){
				Packet randomPacket = generatePacket();
				Slot possibleSlot = warehouseManagement.getBestStoragePlace(randomPacket);
				if(possibleSlot !=null){
					try {
						warehouseManagement.storePacket(randomPacket.getWidth(), randomPacket.getHeight(), randomPacket.getDepth(), randomPacket.getDescription());
					} catch (StorageException e) {
						e.printStackTrace();
					}
				}
			}
		
	}
	public static Packet generatePacket(){
		String description = "autogenerated Packet";
		int width = 1+ (int) Math.random()*2;
		int height = 1+ (int) Math.random()*2;
		int depth = 1+ (int) Math.random()*1;
		return new Packet(width, height, depth, description);
	}
	
	
}
